### ISSUE TITLE
Gemma3 27B DPO keeps going OOM

### ISSUE THREAD

**Issue by sharanmayank** [NVIDIA-NeMo/RL#864]
I have tried many different configurations to run DPO on the Gemma3 27B IT model using the DTensor worker but I keep getting OOM error even at maximum parallelism setting I think.

Please list *minimal* steps or code snippet for us to be able to reproduce the bug.

```
# DPO Algorithm Configuration
dpo:
  max_num_epochs: 2
  max_num_steps: 72
  val_period: 50
  val_batches: 8
  val_global_batch_size: 128
  val_micro_batch_size: 1
  val_at_start: false
  seed: 42

  reference_policy_kl_penalty: 5
  preference_average_log_probs: True # whether normalizing log probs according to the sequence length in preference_loss
  sft_average_log_probs: ${.preference_average_log_probs} # whether normalizing log probs according to the sequence length in sft_loss

  preference_loss_weight: 1 # the coefficient of the preference loss
  sft_loss_weight: 0 # the coefficient of the SFT loss

checkpointing:
  enabled: true
  checkpoint_dir: "results/dpo"
  metric_name: "val_loss"
  higher_is_better: false
  keep_top_k: 10
  save_period: 50

policy:
  model_name: "google/gemma-3-27b-it"
  tokenizer:
    name: "google/gemma-3-27b-it"

  # number of preference samples per batch
  # each preference sample corresponds to a pair of chosen and rejected responses
  # so the actual batch size processed by the model is train_global_batch_size * 2
  train_global_batch_size: 128
  train_micro_batch_size: 1

  ## TODO(@ashors) support
  logprob_batch_size: 1
  max_total_sequence_length: 2048
  precision: "bfloat16"

  dtensor_cfg:
    enabled: true
    cpu_offload: true
    sequence_parallel: true
    activation_checkpointing: true
    tensor_parallel_size: 16
    context_parallel_size: 1
    custom_parallel_plan: null

  dynamic_batching:
    enabled: false

  # makes the training sequence length divisible by the tensor parallel size
  # this is useful for sequence parallel training
  make_sequence_length_divisible_by: 8
  max_grad_norm: 1.0

  optimizer:
    name: "torch.optim.AdamW"
    kwargs:
      lr: 2.0e-6
      weight_decay: 0.0
      betas: [0.9, 0.98]
      eps: 1e-5
      # when using Dtensor, we need to set foreach
      # and fused to False
      foreach: False
      fused: False
    
  scheduler:
    - name: "torch.optim.lr_scheduler.LinearLR"
      kwargs:
        start_factor: 1e-6
        end_factor: 1.0
        total_iters: 10
    - name: "torch.optim.lr_scheduler.LinearLR"
      kwargs:
        start_factor: 1.0
        end_factor: 0.0
        total_iters: 72
    - milestones: [10]
   ```
  

I am running this on 8 H100 nodes. (64 GPUs) using the following command

```
uv run ./examples/run_dpo.py \
  --config ./examples/configs/dpo_gemma3_27b.yaml \
  cluster.num_nodes="${NNODES}" \
  cluster.gpus_per_node="${GPUS_PER_NODE}" \
  data.dataset_name="Tulu3Preference" \
  checkpointing.metric_name="val_loss" \
  checkpointing.higher_is_better=false \
  checkpointing.keep_top_k=10 \
  checkpointing.save_period=50 \
  logger.wandb_enabled=True \
  logger.wandb.name="dpo-aisg-gemma3-27b-${SLURM_JOB_ID}"
```

I have tried with different configs TP in (8,16), cpu offload on and off, activation_checkpointing on and off, sequence_parallelism on and off. Every single one errors out.

Usual error is in the get_logprobs stage

```
ray.exceptions.RayTaskError(OutOfMemoryError): ray::DTensorPolicyWorker.get_reference_policy_logprobs() (pid=2448044, ip=10.182.0.52, actor_id=8cd42d293ecc725adbcb8c490c000000, repr=DTensorPolicyWorker[rank=36])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/nemo-rl/nemo_rl/models/policy/dtensor_policy_worker.py", line 850, in get_reference_policy_logprobs
    reference_logprobs = self.get_logprobs(data, micro_batch_size)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/nemo-rl/nemo_rl/models/policy/dtensor_policy_worker.py", line 758, in get_logprobs
    outputs = self.model(
              ^^^^^^^^^^^
  File "/app/ray_venvs/nemo_rl.models.policy.dtensor_policy_worker.DTensorPolicyWorker/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/ray_venvs/nemo_rl.models.policy.dtensor_policy_worker.DTensorPolicyWorker/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
           ^^^^^^^
  File "/app/ray_venvs/nemo_rl.models.policy.dtensor_policy_worker.DTensorPolicyWorker/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1818, in inner
    hook_result = hook(self, args, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/ray_venvs/nemo_rl.models.policy.dtensor_policy_worker.DTensorPolicyWorker/lib/python3.12/site-packages/torch/distributed/fsdp/_fully_shard/_fsdp_state.py", line 62, in fsdp_hook_wrapper
    return torch._dynamo.disable(func, recursive=True)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/ray_venvs/nemo_rl.models.policy.dtensor_policy_worker.DTensorPolicyWorker/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py", line 838, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/app/ray_venvs/nemo_rl.models.policy.dtensor_policy_worker.DTensorPolicyWorker/lib/python3.12/site-packages/torch/distributed/fsdp/_fully_shard/_fsdp_state.py", line 258, in _post_forward
    output = tree_map(
             ^^^^^^^^^
  File "/app/ray_venvs/nemo_rl.models.policy.dtensor_policy_worker.DTensorPolicyWorker/lib/python3.12/site-packages/torch/utils/_pytree.py", line 1145, in tree_map
    return treespec.unflatten(map(func, *flat_args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/ray_venvs/nemo_rl.models.policy.dtensor_policy_worker.DTensorPolicyWorker/lib/python3.12/site-packages/torch/utils/_pytree.py", line 982, in unflatten
    leaves = list(leaves)
             ^^^^^^^^^^^^
  File "/app/ray_venvs/nemo_rl.models.policy.dtensor_policy_worker.DTensorPolicyWorker/lib/python3.12/site-packages/torch/distributed/fsdp/_fully_shard/_fsdp_common.py", line 181, in _cast_fp_tensor
    return x.to(dtype)
           ^^^^^^^^^^^
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 46.51 GiB. GPU 0 has a total capacity of 79.11 GiB of which 40.95 GiB is free. Including non-PyTorch memory, this process has 38.02 GiB memory in use. Of the allocated memory 29.33 GiB is allocated by PyTorch, and 6.81 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```

A helpful guide on on how to craft a minimal bug report  http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports. 

**Expected behavior**

I expect the training to work. The 4B model works fine with even 4 nodes.

**Environment overview (please complete the following information)**

 - Environment location: Docker on GCP
 - Method of install: [pip install or from source]. Please specify exact commands you used to install.
 - If method of install is [Docker], provide `docker pull` & `docker run` commands used

Custom docker

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- OS version
- PyTorch version
- Python version

**Additional context**

Example: GPU model

**Comment by sharanmayank** [comment]
This issue is fixed after syncing to the main branch. Whatever the cause of the issue was in a previous version of the code is resolved now.

**Comment by qiaochuz-nv** [comment]
## QA RCCA Analysis

RCCA Status: Not Required
RCCA Category: not_required
Test Action: none

Fix PR: N/A
Root Cause: stale/not-a-bug/user-error/workaround closure.
Trigger Config: Gemma3 27B DPO keeps going OOM

Coverage Assessment:
| Area | Result |
|---|---|
| Existing Test | N/A |
| Coverage Status | NOT_REQUIRED |
| Gap | N/A |
| Corrective Action | No RCCA regression test required. |

Conclusion: RCCA classification completed for this closed NeMo-RL GitHub issue.
